package id.telkomsel.merchandise.utils

object Constant {
    const val instalApp = "Dapatkan update tabligh dari ustadz favoritmu hanya di Balligh. " +
            "Install Aplikasinya sekarang juga </downloadlink>"
    const val appName = "Sales"
    const val reffUser = "user"
    const val reffSales = "merchandise"
    const val reffPelanggan = "pelanggan"
    const val reffStore = "store"
    const val reffLoginSalesPhone = "loginSalesPhone"
    const val reffLoginSalesUsername = "loginSalesUsername"
    const val reffLoginPelangganUsername = "loginPelangganUsername"
    const val reffLoginPelangganPhone = "loginPelangganPhone"
    const val reffCreateSales = "createSales"
    const val reffCreatePelanggan = "createPelanggan"
    const val reffUpdatePelanggan = "updatePelanggan"
    const val reffCreateStore = "createStore"
    const val reffEditStore = "editStore"
    const val reffPelangganViewStore = "pelangganViewStore"
    const val reffEditFotoWajahStore = "editFotoWajahStore"
    const val reffEditFotoPelanggan = "editFotoPelanggan"
    const val reffCreateFotoStore = "createFotoStore"
    const val reffUpdateFotoStore = "updateFotoStore"
    const val reffDeleteFotoStore = "deleteFotoStore"
    const val reffGetDaftarFotoStore = "getDaftarFotoStore"
    const val reffCreateFotoIklan = "createFotoIklan"
    const val reffUpdateFotoIklan = "updateFotoIklan"
    const val reffGetDaftarFotoIklan = "getDaftarFotoIklan"
    const val reffCreateStoreFavorit = "createStoreFav"
    const val reffDeleteStoreFavorit = "deleteStoreFav"
    const val reffCreateVoucher = "createVoucher"
    const val reffUpdateSales = "updateSales"
    const val reffUpdateAdmin = "updateAdmin"
    const val reffValidateNewSales = "validateNewSales"
    const val reffValidateNewPelanggan = "validateNewPelanggan"
    const val reffUpdatePasswordSales = "updatePasswordSales"
    const val reffUpdatePasswordPelanggan = "updatePasswordPelanggan"
    const val reffLogoutSales = "logoutSales"
    const val reffLogoutPelanggan = "logoutPelanggan"
    const val reffGetDataSales = "getDataSales"
    const val reffGetDataPelanggan = "getDataPelanggan"
    const val reffGetDataSalesById = "getDataSalesById"
    const val reffForgetPasswordSalesUsername = "forgetPasswordSalesUsername"
    const val reffForgetPasswordSalesPhone = "forgetPasswordSalesPhone"
    const val reffForgetPasswordPelangganUsername = "forgetPasswordPelangganUsername"
    const val reffForgetPasswordPelangganPhone = "forgetPasswordPelangganPhone"
    const val reffDaftarSalesByAdmin = "getDaftarSalesByAdmin"
    const val reffDaftarStoreBySales = "getDaftarStoreBySales"
    const val reffDaftarStoreByPelanggan = "getDaftarStoreByPelanggan"
    const val reffDaftarStoreFavorit = "getDaftarStoreFavorit"
    const val reffDaftarPickSales = "getPickSales"
    const val reffDaftarKategori = "getDaftarKategori"
    const val reffDaftarTopSubKategori = "getTopSubKategori"
    const val reffDataKategori = "getDataKategori"
    const val reffDaftarSubKategoriBySales = "getDaftarSubKategoriBySales"
    const val reffDaftarSubKategori = "getDaftarSubKategori"
    const val reffDaftarSubKategoriFilterKategori = "getDaftarSubKategoriFilterKategori"
    const val reffUpdateStatusSales = "updateStatusSales"
    const val reffUpdateStatusStore = "updateStatusStore"
    const val reffRiwayatPoin = "getRiwayatPoin"
    const val reffDaftarVoucher = "getDaftarVoucher"
    const val reffDaftarVoucherExpired = "getDaftarVoucherExpired"
    const val reffDaftarVoucherBySales = "getDaftarVoucherBySales"
    const val reffDaftarVoucherByAdmin = "getDaftarVoucherByAdmin"
    const val reffUpdateStatusVoucher = "updateStatusVoucher"
    const val reffUpdateRatingVoucher = "updateRatingVoucher"
    const val reffGetAvailableClaimBox = "getAvailableClaimBox"
    const val reffCreateClaimBox = "createClaimBox"
    const val reffUpdateStatusVoucherBySales = "updateStatusVoucherBySales"

    const val reffProvinsi = "getProvinsi"
    const val reffKabupaten = "getKabupatenByProvinsi"
    const val reffKecamatan = "getKecamatanByKabupaten"
    const val reffKelurahan = "getKelurahanByKecamatan"
    const val reffInfoApps = "getInfoApps"
    const val reffCheckToken = "checkTokenSales"

    const val reffDataModel = "dataModel"
    const val reffId = "id"
    const val reffFolder = "folder"
    const val reffName = "name"

    const val reffURL = "http://192.168.1.7:8000"
//    const val reffURL = "https://admin-teman.com"
//    const val reffURL = "http://192.168.43.7:8000"
    const val reffBaseURL = "$reffURL/api/"
    const val reffBaseURLUploadFoto = "$reffURL/api/uploadFoto"

    const val defaultLatitude = -5.1365727
    const val defaultLongitude = 119.4394061

    const val reffSuccess = "Success"
    const val reffSuccessRegister = "Berhasil mendaftar, mohon tunggu proses verifikasi dalam waktu 1x24 jam"
    const val reffSuccessRegisterAgain = "Berhasil mendaftar ulang, mohon tunggu proses verifikasi dalam waktu 1x24 jam"
    const val reffSuccessRegisterPelanggan = "Berhasil mendaftar"
    const val reffDataCanBeUsed = "Data bisa digunakan untuk mendaftar!"

    const val codeRequestFoto = 100
    const val codeRequestGallery = 1
    const val codeRequestScanner = 100
    const val codeRequestLocation = 101
    const val codeRequestPhone = 1
    const val codeRequestLocationUpdate = 10
    const val codeRequestResultCrop = 400

    const val defaultTempFoto = "https://www.google.co.id/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png"
    const val timeFormat = "HH:mm"
    const val dateFormat1 = "dd-M-yyyy"
    const val dateFormat2 = "dd-MMM-yyyy"
    const val dateFormat3 = "dd MMM yyyy"
    const val dateFormat4 = "yyyy-MM-dd"
    const val emailFormat = "[a-zA-Z0-9._-]+@[a-z]+\\.+[a-z]+"

    const val phone = "noHp"
    const val nama = "nama"
    const val token = "token"
    const val username = "username"
    const val provinsi = "provinsi"
    const val noHp = "noHp"

    const val personal = "Personal"

    const val ahlanWaSahlan = "Ahlan Wa Sahlan"
    const val noMessage = "Silahkan mengirim pesan untuk memulai obrolan"
    const val noListMessage = "Afwan, Anda belum mempunyai pesan"
    const val noData = "Afwan, tidak ada data yang ditemukan"
    const val noRequest = "Afwan, belum ada permintaan verifikasi"
    const val alertLogout = "Apakah Anda yakin ingin keluar dari akun?"
    const val alertHapus = "Apakah Anda yakin ingin menghapus data akun anda?"
    const val batalPermintaan = "Batalkan permintaan"
    const val batalAfiliasi = "PERMINTAAN TERKIRIM / BATALKAN"
    const val batalNaib = "PERMINTAAN NAIB TERKIRIM / BATALKAN"
    const val attention = "Perhatian"
    const val yakin = "Yakin"
    const val yakinBatal = "Yakin ingin membatalkan permintaan?"
    const val iya = "Iya"
    const val baik = "Baik"
    const val batal = "Batal"
    const val tolak = "TOLAK"
    const val statusVerifikasi = "statusVerifikasi"
    const val terima = "TERIMA"
    const val tidak = "Tidak"
    const val selesai = "Selesai"
    const val lewati = "Lewati"
    const val keluar = "Keluar"
    const val online = "Online"
    const val offline = "Offline"
    const val wait = "Mohon tunggu..."

    const val terkonfirmasi = "Terkonfirmasi"
    const val belum_terkonfirmasi = "Belum terkonfirmasi"
    const val hapus_pesan = "Hapus pesan?"

    const val manual = "manual"
    const val invalid = "invalid"
    const val status = "status"
    const val active = "active"
    const val pending = "pending"
    const val switch = "switch"
    const val request = "request"

    const val rejected = "rejected"
    const val inactive = "inactive"
    const val expired = "expired"
    const val notused = "notused"
    const val read = "read"
    const val unread = "unread"
    const val sended = "sended"
    const val message = "message"

    const val statusRequest = "request"
    const val statusDeclined = "declined"
    const val statusActive = "active"
    const val statusBanned = "banned"

    const val statusDiproses = "Diproses"
    const val statusDisetujui = "Disetujui"
    const val statusDitolak = "Ditolak"
    const val statusPromoSelesai = "Promo Selesai"
    const val statusStokHabis = "Stok Habis"

    const val levelUser = "User"
    const val level = "level"
    const val login = "login"
    const val levelChannel = "Channel"
    const val levelDLS = "DLS"
    const val levelSales = "Sales"
    const val levelPelanggan = "Pelanggan"

    const val requestSales = "Request Sales"
    const val pendaftaranSales = "Request Sales"
    const val tervalidasiSales = "Tervalidasi Sales"
    const val requestStore = "Tervalidasi Store"
    const val tervalidasiStore = "Request Store"
    const val akun = "Akun"
    const val favorit = "Favorit"
    const val storeFavorit = "Store Favorit"
    const val beranda = "Beranda"
    const val voucher = "Voucher"
    const val scanVoucher = "Scan Voucher"
    const val riwayatPoin = "Riwayat Poin"

    const val dataModelFotoProfil = "FotoProfil"
    const val dataModelFotoDepanKendaraan = "FotoDepanKendaraan"
    const val dataModelFotoBelakangKendaraan = "FotoBelakangKendaraan"
    const val dataModelFotoWajah = "FotoWajah"
    const val dataModelFotoSeluruhBadan = "FotoSeluruhBadan"

    const val folderFotoProfil = "/assets/sales/profil/"
    const val folderFotoDepanKendaraan = "/assets/sales/kendaraan/depan/"
    const val folderFotoBelakangKendaraan = "/assets/sales/kendaraan/belakang/"
    const val folderFotoWajah = "/assets/sales/wajah/"
    const val folderFotoSeluruhBadan = "/assets/sales/badan/"
    const val pendaftaranBerhasil = "Pendaftaran Berhasil"
    const val berhasil = "Berhasil"

    const val pilihKategori = "Pilih Kategori"
    const val pilihProvinsi = "Pilih Provinsi"
    const val pilihKabupaten = "Pilih Kota/Kabupaten"
    const val pilihStore = "Pilih Store"
    const val pilihKecamatan = "Pilih Kecamatan"
    const val pilihKelurahan = "Pilih Kelurahan"

    const val noDataWilayah = "Tidak ada data wilayah"
    const val noDataKategori = "Tidak ada data kategori"
    const val noSalesRequest = "Semua Sales telah divalidasi"
    const val noSales = "Maaf, belum ada data merchandise"
    const val noStoreRequest = "Semua store telah divalidasi"
    const val noStore = "Maaf, belum ada data store"
    const val noStoreFavorit = "Maaf, belum ada data store favorit"
    const val noKategori = "Maaf, belum ada data kategori"

    const val konfirmasi = "Konfirmasi"


    const val noHpPemilik = "Nomor HP Pemilik"
    const val noHpSales = "Nomor HP Sales"
    const val formSelectNumber = "Mohon pilih nomor HP untuk verifikasi kode OTP"

    const val formUpdateSales = "Pendaftaran akun merchandise Anda ditolak, dengan alasan"
    const val loginBerhasil = "Login Berhasil"

}