package id.telkomsel.merchandise.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class ModelSales(
    var id: Int = 0,
    var status: String = "",
    var comment: String = "",
    var username: String = "",
    var password: String = "",
    var level: String = "",
    var email: String = "",
    var pengalaman_kerja: String = "",
    var nama_lengkap: String = "",
    var nama_panggilan: String = "",
    var jenis_kelamin: String = "",
    var status_pernikahan: String = "",
    var jumlah_anak: String = "",
    var tempat_lahir: String = "",
    var tgl_lahir: String = "",
    var alamat: String = "",
    var latitude: String = "",
    var longitude: String = "",
    var provinsi: String = "",
    var kabupaten: String = "",
    var kecamatan: String = "",
    var kelurahan: String = "",
    var regional: String = "",
    var branch: String = "",
    var cluster: String = "",
    var no_hp_sales: String = "",
    var no_wa_sales: String = "",
    var verified_phone: String = "",
    var kepemilikan_sim: String = "",
    var nomor_polisi: String = "",
    var kategori_motor: String = "",
    var foto_profil: String = "",
    var foto_depan_kendaraan: String = "",
    var foto_belakang_kendaraan: String = "",
    var foto_wajah: String = "",
    var foto_seluruh_badan: String = "",
    var token: String = "",
    var created_at: String = "",
    var updated_at: String = "",
    ) : Parcelable